# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_DATABASE: image
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8081